var clickTag = "";
var bannerJson = {
  hash: "bxkiof8nr",
  userId: "262561",
  banner: {
    properties: {
      status: "publish",
      name: "Nike Animated banner",
      width: 336,
      height: 280,
      loop: false,
      imageQuality: 90,
      bannerUrl: "",
      urlTarget: "_blank",
      useHandCursor: true,
      useBannerEntireArea: true,
      bannerSize: "300 x 250 - Medium rectangle",
      customSize: true,
      presetSize: false,
      backgroundColor: {
        type: "solid",
        scolor: "#212121",
        scolor: "coral",
        borderColor: "#3d3d3d",
        useBorder: false,
        scaleMode: "crop",
        horizontalAlign: "center",
        verticalAlign: "middle",
      },
      backgroundOverColor: "#212121",

      lastId: 25,
      useBorder: false,
      version: 2,
    },
    elements: [
      {
        properties: {
          id: 21,
          type: "slide",
          duration: 7,
          stopSlide: false,
          backgroundColor: {
            type: "none",
            scolor: "#3d3d3d",
            useBorder: true,
          },
          transition: {
            type: "none",
            crosstype: "hide",
            direction: "r2l",
            duration: 0.3,
            tween: "Strong",
            ease: "out",
            slidePosX: 0,
            slidePosY: 0,
            alphaOffset: 0,
            slideOffset: 0,
            blurAmount: 10,
          },
        },
        elements: [
          {
            properties: {
              id: 22,
              layerName: "Button 1 - SHOP.NIKE.COM",
              buttonLabel: "SHOP.NIKE.COM",
              backgroundColor: { type: "solid", scolor: "#212121" },
              backgroundOverColor: "#212121",
              labelStyle: {
                fontFamily: "monospace",
                fontDesign: "400",
                fontStyle: "normal",
                fontType: "google",
                fontWeight: "400",
                fontSize: "12",
                color: "#ffffff",
                letterSpacing: "1",
              },
              labelShadow: {
                useShadow: false,
                hShadow: 5,
                vShadow: 5,
                blur: 5,
                color: "rgba(255,0,0,0.5)",
              },
              labelOffsetX: 0,
              labelOffsetY: 0,
              dropShadow: {
                useShadow: false,
                hShadow: 2,
                vShadow: 2,
                blur: 3,
                spread: 0,
                color: "rgba(102,102,102,0.5)",
              },
              opacity: 100,
              border: { color: "rgba(0, 0, 0, 1)", weight: 0, radius: 0 },
              x: 82,
              width: 173,
              y: 211,
              height: 36,
              buildIn: {
                type: "slide",
                direction: "l2r",
                duration: 0.5,
                delay: 0.8,
                tween: "Strong",
                ease: "easeOut",
                slidePosX: 50,
                slidePosY: 0,
                alphaOffset: 0,
                slideOffset: 100,
                blurAmount: 10,
                zoom: 8,
              },
              buildOut: {
                type: "slide",
                direction: "l2r",
                duration: 0.5,
                delay: 2.7,
                tween: "Strong",
                ease: "easeOut",
                slidePosX: 50,
                slidePosY: 0,
                alphaOffset: 0,
                slideOffset: 100,
                blurAmount: 10,
                zoom: 8,
              },
              actions: [],
              visible: true,
            },
            oId: 0,
            eh: "ipe99skshfflxr",
            eId: 103,
            type: "layer",
            layerType: "button",
          },
          {
            properties: {
              id: 23,
              layerName: "Text 2 - NIKES ON FIRE",
              text: "NIKES ON FIRE",
              fontType: "google",
              fontUrl: null,
              fontFamily: "monospace",
              fontDesign: "400",
              fontWeight: "400",
              fontStyle: "normal",
              fontSize: "48",
              color: "#fff",
              alignment: "center",
              lineHeight: "1.3",
              letterSpacing: "-1",
              textTransform: "none",
              textDecoration: "none",
              textShadow: {
                useShadow: false,
                hShadow: 2,
                vShadow: 2,
                blur: 3,
                color: "rgba(0,0,0,0.5)",
              },
              blur: { useBlur: false, pixels: 2 },
              opacity: 100,
              rotation: 0,
              x: 30,
              width: 276,
              y: 129,
              height: 62,
              buildIn: {
                type: "slide",
                direction: "r2l",
                duration: 0.5,
                wordsDuration: 1,
                wordsAppearOrder: "random",
                delay: 0.4,
                tween: "Strong",
                ease: "easeOut",
                slidePosX: 50,
                slidePosY: 0,
                alphaOffset: 0,
                slideOffset: 100,
                blurAmount: 10,
                zoom: 8,
              },
              buildOut: {
                type: "slide",
                direction: "r2l",
                duration: 0.5,
                wordsDuration: 1,
                wordsAppearOrder: "random",
                delay: 3.4,
                tween: "Strong",
                ease: "easeOut",
                slidePosX: 50,
                slidePosY: 0,
                alphaOffset: 0,
                slideOffset: 100,
                blurAmount: 10,
                zoom: 8,
              },
              actions: [],
              visible: true,
              backgroundColor: null,
            },
            oId: 1,
            eh: "ipe9botgjs8aor",
            eId: 101,
            type: "layer",
            layerType: "text",
          },
          {
            properties: {
              id: 24,
              layerName: "Text 1 - THIS MONDAY",
              text: "THIS MONDAY",
              fontType: "google",
              fontUrl: null,
              fontFamily: "monospace",
              fontDesign: "400",
              fontWeight: "400",
              fontStyle: "normal",
              fontSize: "49",
              color: "#000000",
              alignment: "center",
              lineHeight: 1.4,
              letterSpacing: "-1",
              textTransform: "none",
              textDecoration: "none",
              textShadow: {
                useShadow: false,
                hShadow: 2,
                vShadow: 2,
                blur: 3,
                color: "rgba(0,0,0,0.5)",
              },
              blur: { useBlur: false, pixels: 2 },
              opacity: 100,
              rotation: 0,
              x: 29,
              width: 279,
              y: 75,
              height: 69,
              buildIn: {
                type: "slide",
                direction: "l2r",
                duration: 0.5,
                wordsDuration: 1,
                wordsAppearOrder: "random",
                delay: 0,
                tween: "Strong",
                ease: "easeOut",
                slidePosX: 50,
                slidePosY: 0,
                alphaOffset: 0,
                slideOffset: 100,
                blurAmount: 10,
                zoom: 8,
              },
              buildOut: {
                type: "slide",
                direction: "l2r",
                duration: 0.5,
                wordsDuration: 1,
                wordsAppearOrder: "random",
                delay: 4,
                tween: "Strong",
                ease: "easeOut",
                slidePosX: 50,
                slidePosY: 0,
                alphaOffset: 0,
                slideOffset: 100,
                blurAmount: 10,
                zoom: 8,
              },
              actions: [],
              visible: true,
              backgroundColor: null,
            },
            oId: 2,
            eh: "ipe9dukan019k9",
            eId: 101,
            type: "layer",
            layerType: "text",
          },
          {
            properties: {
              id: 25,
              layerName: "Nike Logo",
              url: "8481f72a95c51a01b8347dbf55325134",
              scaleMode: "crop",
              horizontalAlign: "center",
              verticalAlign: "middle",
              contentScale: 100,
              contentOffsetX: 50,
              contentOffsetY: 50,
              dropShadow: {
                useShadow: false,
                hShadow: 2,
                vShadow: 2,
                blur: 3,
                color: "rgba(0,0,0,0.5)",
              },
              adjustColor: {
                useAdjustColor: false,
                brightness: 0,
                contrast: 0,
                saturate: 0,
                hue: 0,
              },
              blur: { useBlur: false, pixels: 2 },
              opacity: 100,
              rotation: 0,
              flip: "none",
              x: 144,
              width: 48,
              y: 19,
              height: 48,
              oWidth: 256,
              oHeight: 256,
              buildIn: {
                type: "alpha",
                direction: "r2l",
                duration: 0.7,
                delay: 1.3,
                tween: "Quad",
                ease: "easeIn",
                slidePosX: 50,
                slidePosY: 0,
                alphaOffset: 0,
                slideOffset: 50,
                blurAmount: 10,
                zoom: 8,
              },
              buildOut: {
                type: "alpha",
                direction: "r2l",
                duration: 1,
                delay: 3.2,
                tween: "Quad",
                ease: "easeIn",
                slidePosX: 50,
                slidePosY: 0,
                alphaOffset: 0,
                slideOffset: 50,
                blurAmount: 10,
                zoom: 8,
              },
              actions: [],
              visible: true,
              backgroundColor: null,
              localUrl: "logo.png",
            },
            oId: 3,
            eh: "ipe9h01td3rf6r",
            eId: 102,
            type: "layer",
            layerType: "image",
          },
        ],
        type: "slide",
        aId: 3,
        ah: "ipe9775gnvcxr",
      },
    ],
  },
};
var bannerConfig = {
  photosUrl: "../img/",
  embedUrl: "../img/",
  startSlide: 0,
  noAnimation: false,
  preview: false,
  printScreen: false,
  showOnlyOneSlide: false,
  video: false,
  download: false,
  env: "live",
};
var embedCanvas = new EmbedCanvas();
document.addEventListener("DOMContentLoaded", function () {
  embedCanvas.init(document.getElementById("bs"), bannerJson, bannerConfig);
});
